### ISSUE TITLE
System.Runtime Issue

### ISSUE THREAD

**Issue by zxcdani** [picoe/Eto#365]
When I try to Run the Projects - Winforms, Wpf, Gtk2 and Gtk3 - an Assembly Not Referenced error shows up.

> Error CS0012: The type `System.IDisposable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 

and this

> Error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 

Tried to change the targeted frameworks but I still get this error.

I am using Monodevelop on Ubuntu, newly installed, all packages are installed.

**Comment by cwensley** [comment]
To compile the PCL version of Eto on ubuntu, you need to use the latest mono packages from [here](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives).  You also need to install the *referenceassemblies-pcl* package.  Otherwise, you can compile the net40 solution instead, which should work on Ubuntu with its standard mono 3.2.x.

When running your compiled app, the net45/pcl version of Eto should run on mono 3.2.x, so this is only a development requirement.

Information about this is on the [contributing guide](https://github.com/picoe/Eto/wiki/Contributing#linux) in the wiki.

**Comment by zxcdani** [comment]
I did install all the mono packages as well as the pcl package, but I still get the Runtime error. My target framework for my Library is Mono / .NET 4.5 but I still, I can't compile my projects.

**Comment by cwensley** [comment]
Great! so it is working now?

**Comment by zxcdani** [comment]
Yes, it's working great now with Linux, Mac and Windows but I'm now having problems with Wpf, specifically Presentation Framework.

**Comment by cwensley** [comment]
What are the problems with Wpf?  Is it the same System.Runtime issue or is it a different issue?

**Comment by zxcdani** [comment]
Oh, it's a different issue. I will close this one now, sorry for that.

**Comment by cwensley** [comment]
no problem at all!  thanks.  btw, if there's any "gotcha's" that you are uncovering, it could possibly use an entry in the [Troubleshooting](https://github.com/picoe/Eto/wiki/Troubleshooting-%26-Common-Problems) wiki page.
