### ISSUE TITLE
Wpf missing reference?

### ISSUE THREAD

**Issue by DWAK-ATTK** [picoe/Eto#1271]
I'm on a mac (10.14.1 if it matters) and issue the following command in an empty (~/AlarmThingy) directory:

    dotnet new etoapp -sln -m code -s

This results in 4 project directories: `AlarmThingy`, `AlarmThingy.Gtk`, `AlarmThingy.Mac`, and `AlarmThingy.Wpf`, as well as `AlarmThingy.sln` file.

Next run:

    msbuild

I receive 4 warnings (no biggie) and 1 Error:

> "/Users/DWAK/AlarmThingy/AlarmThingy.sln" (default target) (1) ->
"/Users/DWAK/AlarmThingy/AlarmThingy.Wpf/AlarmThingy.Wpf.csproj" (default target) (5) ->
(CoreCompile target) ->
  Program.cs(2,7): error CS0246: The type or namespace name 'Eto' could not be found (are you missing a using directive or an assembly reference?) [/Users/DWAK/AlarmThingy/AlarmThingy.Wpf/AlarmThingy.Wpf.csproj]

I checked the `AlarmThingy.Wpf.csproj` file and see:

```
 <ItemGroup>
    <PackageReference Include="Eto.Platform.Wpf">
      <Version>2.4.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlarmThingy\AlarmThingy.csproj">
      <Project>{9AE5C74C-C73D-48F8-B800-0FD9698C7C2A}</Project>
      <Name>AlarmThingy</Name>
    </ProjectReference>
  </ItemGroup>
```

In VSCode's output window, OmniSharp also reports:
> [warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/DWAK/AlarmThingy/AlarmThingy/bin/Debug/netstandard1.6/AlarmThingy.dll'

Any thoughts on what could be wrong?

**Comment by cwensley** [comment]
try `nuget restore` before building.  Doing this works on my Mac with mono 5.12 and dotnet sdk 2.1.403:

```bash
dotnet new -i "Eto.Forms.Templates::*"
mkdir AlarmThingy
cd AlarmThingy
dotnet new etoapp -sln -m code -s
nuget restore
msbuild
```

What version of mono and dotnet sdk do you have?

**Comment by DWAK-ATTK** [comment]
Oh my word, that did it.  I'm such a dummy-head.

Thank you!

using 
dotnet: 2.2.100-preview2-009404
and mono: Mono JIT compiler version 5.12.0.309 (2018-02/39d89a335c8 Thu Sep 27 06:54:53 EDT 2018)

**Comment by cwensley** [comment]
No problem. (;
